on:
  push:
    branches: [ 'main' ]

jobs:
  scripts:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Remove from remote servers
        run: sh /home/cloud/scripts/github/actions/remove.sh
      - name: Deploy to remote servers
        run: |
          sh /home/cloud/scripts/github/actions/deploy.sh scripts
          rm -rf /home/cloud/scripts
          mkdir /home/cloud/scripts
          rsync -av --progress $GITHUB_WORKSPACE /home/cloud/scripts --exclude .git/ --exculde .gitignore