on: [ 'push' ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Delete old scripts folder
      run: rm -rf /home/cloud/scripts/
    - name: Create new scripts folder
      run: mkdir /home/cloud/scripts/
    - name: Copy all updated files to scripts folder
      working-directory: ${{ github.workspace }}
      run: cp * /home/cloud/scripts
