on: [ 'push' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Removing old script data from remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEDICATED_1_HOST_ADDRESS }}
        username: ${{ secrets.DEDICATED_USER }}
        key: ${{ echo -e secrets.DEDICATED_SSH_KEY | base64 --decode }}
        script: rm -rf /home/cloud/scripts/
    - name: Deploy project to remote servers
      uses: hyrendev/scp-action@0.1-ALPHA
      with:
        remote: /home/cloud/output/
        files: |
          [
            "${{ github.workspace }}/"
          ]
        servers: |
          [
            {
              "host": "${{ secrets.DEDICATED_1_HOST_ADDRESS }}",
              "port": "${{ secrets.DEDICATED_PORT }}",
              "user": "${{ secrets.DEDICATED_USER }}",
              "private_key": "${{ secrets.DEDICATED_SSH_KEY }}"
            }
          ]